config/routes.rb
Rails.application.routes.draw do
  
  get '/school_admins' => 'users#index', :defaults => { role: 'school_admin' }
  get '/students' => 'users#index', :defaults => { role: 'student' }

  resources :users, only: [:index, :new, :create]
  resources :schools do
    resources :courses do
      resources :batches do
        member do
          get :pending_enrollment_requests
          get :progress
          get :approved_students
        end
      end
    end
  end

  resources :batches, only: [] do
    resources :enrollment_requests do
      get :approve
      get :decline
    end
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'schools#index'
  # root to: 'batches#index', constraints: lambda { |user| user.student? }
  # devise_for :users, controllers: {
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations',
  #     sessions: 'users/sessions',
  #     invitations: 'users/invitations',
  # }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
end

app/models/enrollment_request.rb
class EnrollmentRequest < ApplicationRecord
  belongs_to :batch
  belongs_to :student, -> { where "users.role = 2" }, class_name: "User", foreign_key: "student_id"
  belongs_to :approver, class_name: "User", foreign_key: "approved_by", optional: true

  validates :student_id, uniqueness: { scope: :batch_id, 
    message: "already exists for this batch"
  }

  enum status: { pending: 0, approved: 1, decline: 2 }
  enum progress: { not_start: 0, started: 1, completed: 2 }

  def approve!(approved_by_id)
    self.update(status: 'approved', approved_by: approved_by_id, approved_at: Time.now, progress: "started")
  end

  def progress!
    self.update(progress: "completed")
  end
end

app/controllers/enrollment_requests_controller.rb
class EnrollmentRequestsController < ApplicationController
  load_and_authorize_resource
  before_action :find_batch
  before_action :set_enrollment_request, only: %i[ show edit update destroy approve decline ]

  # GET /enrollment_requests or /enrollment_requests.json
  def index
    @enrollment_requests = @batch.enrollment_requests.all
  end

  # GET /enrollment_requests/1 or /enrollment_requests/1.json
  def show
  end

  # GET /enrollment_requests/new
  def new
    @enrollment_request = @batch.enrollment_requests.new
  end

  # GET /enrollment_requests/1/edit
  def edit
  end

  # POST /enrollment_requests or /enrollment_requests.json
  def create
    @enrollment_request = @batch.enrollment_requests.new(enrollment_request_params)

    respond_to do |format|
      if @enrollment_request.save
        @enrollment_request.approve!(current_user.id) unless current_user.student?
        format.html { redirect_to batch_enrollment_request_url(@batch, @enrollment_request), notice: "Enrollment request was successfully created." }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollment_requests/1 or /enrollment_requests/1.json
  def update
    respond_to do |format|
      if @enrollment_request.update(enrollment_request_params)
        format.html { redirect_to batch_enrollment_request_url(@batch, @enrollment_request), notice: "Enrollment request was successfully updated." }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollment_requests/1 or /enrollment_requests/1.json
  def destroy
    @enrollment_request.destroy

    respond_to do |format|
      format.html { redirect_to batch_enrollment_requests_url(@batch), notice: "Enrollment request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def approve
    @enrollment_request.approve!(current_user.id)
    redirect_back fallback_location: root_path
  end

  def decline
    @enrollment_request.decline!
    redirect_back fallback_location: root_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment_request
      @enrollment_request = EnrollmentRequest.find(params[:id] || params[:enrollment_request_id])
    end

    def find_batch
      @batch = Batch.find(params[:batch_id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_request_params
      params.require(:enrollment_request).permit(:batch_id, :student_id, :status)
    end
end

app/helpers/enrollment_requests_helper.rb
module EnrollmentRequestsHelper
end

app/views/enrollment_requests/_form.html.erb
<%= form_with(model: enrollment_request, url: [@batch, @enrollment_request]) do |form| %>
  <% if enrollment_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrollment_request.errors.count, "error") %> prohibited this enrollment_request from being saved:</h2>

      <ul>
        <% enrollment_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <label>You're enrolling for batch named: <%= @batch.name %></label>
  </p>
  <% if can?(:manage, @enrollment_request) && (current_user.school_admin? || current_user.admin?) %>
    <div class="field">
      <%= form.label :Student %>
      <%= form.select :student_id, options_for_select(User.student.map { |student| ["#{student.first_name} #{student.last_name}", student.id] }), {:prompt => 'Select Student'} %>
    </div>
  <% elsif current_user.student? %>
    <%= form.hidden_field :student_id, value: current_user.id %>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrollment_requests/edit.html.erb
<h1>Editing Enrollment Request</h1>

<%= render 'form', enrollment_request: @enrollment_request %>

<%= link_to 'Show', batch_enrollment_request_path(@batch, @enrollment_request) %> |
<%= link_to 'Back', batch_enrollment_requests_path(@batch) %>

app/views/enrollment_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrollment Requests</h1>

<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Student</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrollment_requests.includes(:batch, :student).each do |enrollment_request| %>
      <tr>
        <td><%= enrollment_request.batch.name %></td>
        <td><%= enrollment_request.student&.full_name %></td>
        <td><%= enrollment_request.status %></td>
        <td><%= link_to 'Show', batch_enrollment_request_path(@batch, enrollment_request) %></td>
        
        <% if can? :manage, EnrollmentRequest %>
          <td><%= link_to 'Edit', edit_batch_enrollment_request_path(@batch, enrollment_request) %></td>
          <td><%= button_to 'Destroy', batch_enrollment_request_path(@batch, enrollment_request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if can? :manage, EnrollmentRequest %>
  <%= link_to 'New Enrollment Request', new_batch_enrollment_request_path %>
<% end %>
<%= link_to 'Back', school_course_batches_path(@batch.school, @batch.course) %>

app/views/enrollment_requests/new.html.erb
<h1>New Enrollment Request</h1>

<%= render 'form', enrollment_request: @enrollment_request %>

<%= link_to 'Back', batch_enrollment_requests_path(@batch) %>

app/views/enrollment_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch:</strong>
  <%= @enrollment_request.batch&.name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @enrollment_request.student&.full_name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @enrollment_request.status %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @enrollment_request.approved_at %>
</p>

<% if current_user.admin? %>
  <p>
    <strong>Approved by:</strong>
    <%= @enrollment_request.approver&.full_name %>
  </p>
<% end %>
<% if can? :manage, @enrollment_request %>
  <%= link_to 'Edit', edit_batch_enrollment_request_path(@batch, @enrollment_request) %> |
<% end %>
<%= link_to 'Back', batch_enrollment_requests_path(@batch) %>