config/routes.rb
Rails.application.routes.draw do
  
  get '/school_admins' => 'users#index', :defaults => { role: 'school_admin' }
  get '/students' => 'users#index', :defaults => { role: 'student' }

  resources :users, only: [:index, :new, :create]
  resources :schools do
    resources :courses do
      resources :batches do
        member do
          get :pending_enrollment_requests
          get :progress
          get :approved_students
        end
      end
    end
  end

  resources :batches, only: [] do
    resources :enrollment_requests do
      get :approve
      get :decline
    end
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'schools#index'
  # root to: 'batches#index', constraints: lambda { |user| user.student? }
  # devise_for :users, controllers: {
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations',
  #     sessions: 'users/sessions',
  #     invitations: 'users/invitations',
  # }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :admin, -> { where "users.role = 1" }, class_name: "User", foreign_key: "admin_id"
                        # role 1 here is the school admin

  has_many :courses, dependent: :destroy
  has_many :batches, dependent: :destroy
  validates :name, presence: true
  validates :email, presence: true, format: URI::MailTo::EMAIL_REGEXP
  
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  load_and_authorize_resource
  before_action :set_school_admins, only: %i[ new edit ]

  # GET /schools or /schools.json
  def index
    if current_user.school_admin?
      @schools = School.where(admin_id: current_user.id)
    else
      @schools = School.all
    end
  end

  # GET /schools/1 or /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools or /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_url(@school), notice: "School was successfully created." }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1 or /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to school_url(@school), notice: "School was successfully updated." }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1 or /schools/1.json
  def destroy
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url, notice: "School was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_school_admins
      @school_admins = User.school_admin
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name, :email, :address, :admin_id)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label 'School Admin' %>
    <%= form.select :admin_id, options_for_select(User.school_admin.map { |school_admin| ["#{school_admin.first_name} #{school_admin.last_name}", school_admin.id] }), {:prompt => 'Select School Admin'} %>
    
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>School Admin</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @schools.includes(:admin).each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.email %></td>
        <td><%= "#{school.admin.full_name}" %></td>
        
        <% if can? :read, Course %>
          <td><%= link_to 'Courses', school_courses_path(school_id: school.id) %></td> 
        <% end %>
        
        <% if can? :read, school %>
          <td><%= link_to 'Show', school %></td>
        <% end %>

        <% if can? :update, school %>
          <td><%= link_to 'Edit', edit_school_path(school) %></td> 
        <% end %>
        <% if can? :destroy, school %>
          <td><%= button_to 'Destroy', school_path(school), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, School %>
  <%= link_to 'New School', new_school_path %>
<% end %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @school.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @school.address %>
</p>

<% if can? :edit, @school %>
  <%= link_to 'Edit', edit_school_path(@school) %> |
<% end %>
<%= link_to 'Courses', school_courses_path(@school) %> |
<%= link_to 'Back', schools_path %>