config/routes.rb
Rails.application.routes.draw do
  
  get '/school_admins' => 'users#index', :defaults => { role: 'school_admin' }
  get '/students' => 'users#index', :defaults => { role: 'student' }

  resources :users, only: [:index, :new, :create]
  resources :schools do
    resources :courses do
      resources :batches do
        member do
          get :pending_enrollment_requests
          get :progress
          get :approved_students
        end
      end
    end
  end

  resources :batches, only: [] do
    resources :enrollment_requests do
      get :approve
      get :decline
    end
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'schools#index'
  # root to: 'batches#index', constraints: lambda { |user| user.student? }
  # devise_for :users, controllers: {
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations',
  #     sessions: 'users/sessions',
  #     invitations: 'users/invitations',
  # }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :course
  belongs_to :school

  has_many :enrollment_requests, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :course_id }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validate  :validate_date_time

  private
    def validate_date_time
      return if start_time.blank? || end_time.blank?

      if start_time < Date.today
        errors.add(:start_time, "can't be in past" )
      elsif end_time < start_time
        errors.add(:end_time, "should be greater than start time" )
      end
    end
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  load_and_authorize_resource
  before_action :find_course
  before_action :set_batch, except: %i[index new create]

  # GET /batches or /batches.json
  def index
    @batches = @course.batches.all
  end

  # GET /batches/1 or /batches/1.json
  def show
    @total_pending_enrollments = @batch.enrollment_requests.pending.count
    @total_approved_enrollments = @batch.enrollment_requests.approved.count
  end

  # GET /batches/new
  def new
    @batch = @school.batches.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches or /batches.json
  def create
    @batch = @course.batches.new(batch_params)
    @batch.school_id = @school.id

    respond_to do |format|
      if @batch.save
        format.html { redirect_to school_course_batch_url(@school, @course, @batch), notice: "Batch was successfully created." }
        format.json { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1 or /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to school_course_batch_url(@school, @course, @batch), notice: "Batch was successfully updated." }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1 or /batches/1.json
  def destroy
    @batch.destroy

    respond_to do |format|
      format.html { redirect_to school_course_batches_path(@school, @course), notice: "Batch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def pending_enrollment_requests
    @pending_enrollment_requests = @batch.enrollment_requests.pending
  end

  def approved_students
    if current_user.student? 
      @approved_students = current_user.classmates(batch_id: @batch.id)
    else
      @approved_students = @batch.enrollment_requests.approved
    end
  end

  def progress
    @batch.enrollment_requests.find_by(student_id: current_user.id)&.progress!
    redirect_to school_course_batch_url(@school, @course, @batch)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_batch
    @batch = @course.batches.find(params[:id])
  end

  def find_course
    @school = School.find(params[:school_id])
    @course = @school.courses.find(params[:course_id])
  end

  # Only allow a list of trusted parameters through.
  def batch_params
    params.require(:batch).permit(:name, :start_time, :end_time)
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= form_with(model: @batch, url: [@school, @course, @batch]) do |form| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
        <% batch.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_field :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_field :end_time, "data-provide" => 'datepicker' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/approved_students.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "#{current_user.student? ? 'Classmates' : 'Students' } for course: #{@course.name} and batch: #{@batch.name}" %></h1>

<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Student</th>
      <th>Student email</th>
      <th>Progress</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if @approved_students.present? %>

      <% @approved_students.includes(:student).each do |approved_student| %>
        <tr>
          <td><%= @batch.name %></td>
          <td><%= approved_student.student&.full_name %></td>
          <td><%= approved_student.student&.email %></td>
          <td><%= approved_student.progress %></td>
          <td><%= link_to 'Show', batch_enrollment_request_path(@batch, approved_student) %></td>
          <% if can? :manage, EnrollmentRequest %>
            <td><%= button_to 'Destroy', batch_enrollment_request_path(@batch, approved_student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<% if can? :create, EnrollmentRequest %>
  <%= link_to 'New Enrollment Request', new_batch_enrollment_request_path(@batch) %>
<% end %>
<%= link_to 'Back', school_course_batches_path(@school, @course) %>

app/views/batches/classmates.html.erb
<p id="notice"><%= notice %></p>

<h1>Students for batch: <%= @batch.name %></h1>


<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Student</th>
      <th>Student email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% if classmates.empty? %>
      <% @classmates.includes(:student).each do |approved_student| %>
        <tr>
          <td><%= @batch.name %></td>
          <td><%= approved_student.student&.full_name %></td>
          <td><%= approved_student.student&.email %></td>
          <td><%= link_to 'Show', batch_enrollment_request_path(@batch, approved_student) %></td>
          <% if can? :manage, EnrollmentRequest %>
            <td><%= button_to 'Destroy', batch_enrollment_request_path(@batch, approved_student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<% if can? :create, EnrollmentRequest %>
  <%= link_to 'New Enrollment Request', new_batch_enrollment_request_path(@batch) %>
<% end %>
<%= link_to 'Back', school_course_batches_path(@school, @course) %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', school_course_batch_path(@school, @course, @batch) %> |
<%= link_to 'Back', school_course_batches_path(@school, @course) %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>School name</th>
      <th>Course name</th>
      <th>Start time</th>
      <th>End time</th>
      <th colspan="3"> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.name %></td>
        <td><%= @school.name %></td>
        <td><%= @course.name %></td>
        <td><%= batch.start_time %></td>
        <td><%= batch.end_time %></td>

        <% if can? :read, batch %>
          <td><%= link_to 'Show', school_course_batch_path(@school, @course, batch) %></td>
        <% end %>

        <% if can? :pending_enrollment_requests, batch %>
        <td><%= link_to 'Show Pending Enrollement Requests', pending_enrollment_requests_school_course_batch_path(@school, @course, batch) %></td>
        <% end %>

        <% if can? :approved_students, batch %>
          <td><%= link_to current_user.student? ? 'Show classmates' : 'Show Batch Students', approved_students_school_course_batch_path(@school, @course, batch) %></td>
        <% end %>

        <% if can? :manage, batch %>
          <td><%= link_to 'Edit', edit_school_course_batch_path(@school, @course, batch) %></td>
          <td><%= button_to 'Destroy', school_course_batch_path(@school, @course, batch), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% if current_user.student? && can?(:progress, batch) %>
          <td><%= link_to 'course progress', progress_school_course_batch_path(@school, @course, batch) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :manage, Batch %>
  <%= link_to 'New Batch', new_school_course_batch_path(school_id: @school.id, course_id: @course.id) %>
<% end %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Back', school_course_batches_path(@school, @course) %>

app/views/batches/pending_enrollment_requests.html.erb
<p id="notice"><%= notice %></p>

<h1>Pending Enorllment Requests</h1>

<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Student</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @pending_enrollment_requests.includes(:student).each do |enrollment_request| %>
      <tr>
        <td><%= @batch.name %></td>
        <td><%= enrollment_request.student&.full_name %></td>
        <td><%= enrollment_request.status %></td>
        <% if can? :manage, EnrollmentRequest %>
          <td><%= link_to 'Approve', batch_enrollment_request_approve_path(batch_id: @batch, enrollment_request_id:enrollment_request) %></td>
          <td><%= link_to 'Decline', batch_enrollment_request_decline_path(batch_id: @batch, enrollment_request_id:enrollment_request) %></td>
          <td><%= button_to 'Destroy', batch_enrollment_request_path(@batch, enrollment_request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if can? :create, EnrollmentRequest %>
  <%= link_to 'New Enrollment Request', new_batch_enrollment_request_path(@batch) %>
<% end %>
<%= link_to 'Back', school_course_batches_path(@school, @course) %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch:</strong>
  <%= @batch.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @batch.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @batch.end_time %>
</p>

<p>
  <strong>Total Pending Enrollment requests</strong>
  <%= @total_pending_enrollments %>
</p>

<p>
  <strong>Total active students</strong>
  <%= @total_approved_enrollments %>
</p>


<% if can? :manage, @batch %>
  <%= link_to 'Edit', edit_school_course_batch_path(@school, @course, @batch) %> |
<% end %>
<% if current_user.student? && can?(:progress, @batch) %>
  <td><%= link_to 'course progress', progress_school_course_batch_path(@school, @course, @batch) %></td>
<% end %>
<%= link_to 'Show Batch Enrollments', batch_enrollment_requests_path(@batch) %> |
<%= link_to 'Back', school_course_batches_path(@school, @course) %> 