config/routes.rb
Rails.application.routes.draw do
  
  get '/school_admins' => 'users#index', :defaults => { role: 'school_admin' }
  get '/students' => 'users#index', :defaults => { role: 'student' }

  resources :users, only: [:index, :new, :create]
  resources :schools do
    resources :courses do
      resources :batches do
        member do
          get :pending_enrollment_requests
          get :progress
          get :approved_students
        end
      end
    end
  end

  resources :batches, only: [] do
    resources :enrollment_requests do
      get :approve
      get :decline
    end
  end
  # devise_scope :user do
  #   root to: "devise/sessions#new"
  # end

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions'
  # }
  devise_for :users, controllers: { sessions: 'users/sessions' }
  root to: 'schools#index'
  # root to: 'batches#index', constraints: lambda { |user| user.student? }
  # devise_for :users, controllers: {
  #     passwords: 'users/passwords',
  #     confirmations: 'users/confirmations',
  #     sessions: 'users/sessions',
  #     invitations: 'users/invitations',
  # }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmeritusAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      <div style="float:right">
        <p>
          <%= link_to "Edit profile", edit_user_registration_path, { class: "nav-link" } %> |
          <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"%>  
        </p>
      </div>
      <p class="alert alert-success">
        Logged in as <strong><%= current_user.email %></strong>
      </p>
      
      <nav class="navbar navbar-expand-md navbar-dark bg-primary">
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active" style="display: inline;">
              <%= link_to "Schools", schools_path, class: "nav-link" %>
            </li>

            <% if current_user.admin? %>
              <li class="nav-item" style="display: inline;">
                <%= link_to "School Admins", school_admins_path, class: "nav-link" %>
              </li>
              <li class="nav-item" style="display: inline;">
                <%= link_to "Students", students_path, class: "nav-link" %>
              </li>
            <% end %>
            
          </ul>
        </div>
      </nav>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
    </p>

    <%= yield %>
  </body>
</html>